# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d7a95693239f85df93716fed661fb757420b76763d9235be1d40496aa2e7429ff60a871001ad27ca06235b73096098be32cc133d16949664ba9dde6b24f0ae

test:
  secret_key_base: 6a58b598ef25a285a48b6f2f3173351d53501353a557b806ef661ff65a116a4ed86717cdb2e54b3fe7c26543ffba547762212936c69e94e73ea0cf7bb2cb479b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
